export default Object.freeze({
  FETCH_PRODUCERS_SUCCESS: 'Producers/FETCH_PRODUCERS_SUCCESS',
  FETCH_BLACK_LIST_SUCCESS: 'Producers/FETCH_BLACK_LIST_SUCCESS',
  PRODUCERS_RELOAD: 'Producers/PRODUCERS_RELOAD',
  PRODUCERS_UPDATE: 'Producers/PRODUCERS_UPDATE',
  BLACK_LIST_UPDATE: 'Producers/BLACK_LIST_UPDATE',
  TOGGLE_PRODUCER_SELECTION: 'Producers/TOGGLE_PRODUCER_SELECTION',
  SET_FILTER_INPUT_VALUE: 'Producers/SET_FILTER_INPUT_VALUE',
});
